# Defaults
title:              Morning Hypertext Fragments
description:        All Things Under Analyzed
owner:              Ryan Johnson
header-img:         img/home-bg.jpg
email:              ryan@tenthirtyam.org
baseurl:        
url:                http://tenthirtyam.github.io
twitter_username:   tenthirtyam
github_username:    tenthirtyam
linkedin_username:  tenthirtyam

# Conversion
markdown:           kramdown
highlighter:        pygments
permalink:          pretty
paginate:           1
exclude:            ["less","node_modules","Gruntfile.js","package.json","README.md"]
