# Site settings
owner: Ryan Johnson //
title: Morning Hypertext Fragments
header-img: img/home-bg.jpg
email: ryan@tenthirtyam.ogg
description: "All Things Under Analyzed"
baseurl: ""
url: "http://tenthirtyam.github.io"
twitter_username: tenthirtyam
github_username:  tenthirtyam
facebook_username:  tenthirtyam
# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
