# Site Settings
baseurl: 		""
title: 			Morning Hypertext

name: 			Morning Hypertext
description:
url: 			""

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		tenthirtyam
email: 			hello@tenthirtyam.org

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2014 Ryan Johnson.

# Build Settings
permalinks: 	pretty
