# Site settings
title: Morning Hypertext Fragments
header-img: img/home-bg.jpg
email: ryan@tenthirtyam.ogg
description: "MOrning Hypertext Fragments"
baseurl: ""
url: "http://tenthirtyam.github.io"
twitter_username: tentirtyam
github_username:  tenthirtyam
facebook_username:  tenthirtyam
# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
