#blog logo
logo: "/assets/images/logo.jpg"
home: "/assets/images/home.jpg"
avatar: "/assets/images/avatar.jpg"
# blog cover
cover: "/assets/images/home-bg.jpg"

name: 'Ryan Johnson'
author: 'Ryan Johnson'
author_image: "/assets/images/author.jpg"


# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/tenthirtyam
    desc:   Follow Me

  - icon:	linkedin
    url:	https://linkedin.com/in/tenthirtyam
    desc:   Connect Me
  
  - icon:	github
    url:	https://github.com/tenthirtyam
    desc:	Fork Me
  
# Setup
title:              Morning Hypertext Fragments
description:        All Things Under Analyzed</br>Ryan Johnson
email:              ryan@tenthirtyam.org
baseurl:            
url:                http://tenthirtyam.github.io
paginate:           1

# Author
author:
  name:             Ryan Johnson
  image:            "/assets/images/author.jpg" 
  url:              https://twitter.com/tenthirtyam
  email:            ryan@tenthirtyam.org
  github:           tenthirtyam
  twitter:          tenthirtyam
  linkedin:         tenthirtyam
author_image: "/assets/images/author.jpg"  

# Build Settings
markdown:           kramdown
highlighter:        pygments

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title/
relative_permalinks: true

# Exclude Ruby gem stuff
exclude:            ["README.md"]

# Gems
#gems:
#  - jekyll-redirect-from
#  - jekyll-sitemap