# Site
title:
description: by Ryan Johnson
url: "https://tenthirtyam.org"
baseurl: "https://tenthirtyam.org/"
logo: logo.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/radio.png                         # this image will be shown on post list page
  default-post: images/tower.png                      # this image will be shown when post's front matter doesn't specify any image

# Build
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social
#email:             email
twitter:            tenthirtyam
github:             tenthirtyam
linkedin:           tenthirtyam
#youtube:           tenthirtyam
#soundcloud:        tenthirtyam

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
