# Site settings
title: Morning Hypertext
description: by Ryan Johnson
url: "https://tenthirtyam.org"
baseurl: "https://tenthirtyam.org/"
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'tenthirtyam'

author:<table>
<tbody>
<tr>
<td>Service</td>
<td>Process Name</td>
<td>Virtual Machine Restart?</td>
<td>Minimal Uptime</td>
<td>Number of Restarts</td>
</tr>
<tr>
<td>Reverse Proxy</td>
<td>rhttpproxy</td>
<td>No</td>
<td>30 seconds</td>
<td>5</td>
</tr>
<tr>
<td>vCenter Management Web Service</td>
<td>vws</td>
<td>No</td>
<td>30 seconds</td>
<td>5</td>
</tr>
<tr>
<td>Syslog Collector</td>
<td>Syslog</td>
<td>No</td>
<td>30 seconds</td>
<td>5</td>
</tr>
<tr>
<td>vPostgres Database</td>
<td>vmware-vpostgres</td>
<td>No</td>
<td>5 minutes</td>
<td>2</td>
</tr>
<tr>
<td>vCenter Server</td>
<td>vpxd</td>
<td>Yes</td>
<td>1 hour</td>
<td>2</td>
</tr>
<tr>
<td>VSAN Health Check</td>
<td>vsan-health</td>
<td>No</td>
<td>10 minutes</td>
<td>10</td>
</tr>
</tbody>
</table>
  name: Ryan Johnson
  twitter_username: tenthirtyam
  github_username: tenthirtyam
  linkedin_username: tenthirtyam

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
timezone: "America/NewYork"
destination: _site
paginate: 1
permalink: /:year/:month/:day/:title/
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  auto_ids: true
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
